
# Site settings

url: "https://aditisrinivas97.github.io"

baseurl: "/new-website"

# Google tracking id

google-tracking-id: ""

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Aditi Srinivas"
title: "Aditi Srinivas"
description: "Blog and website of Aditi Srinivas, blogging mainly for tech. Opinions expressed are mine."
keywords: "srinivas, aditi, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Cool cool cool cool cool no doubt noo doooubt!"
  - text: "Valar Morghulis. Valar Dohaeris."
  - text: "I'm not great at advice, but can I interest you in a sarcastic comment?"
  - text: "Make memes, not war."
  - text: "Squirrel!"
  - text: "By all means move at a glacial pace. You know how that thrills me."
  - text: "The ratio of people to cake is too big."


me-img: "https://github.com/aditisrinivas97.png?size=500"


color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "aditi-srinivas"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/hackerrank.png"
    date: "January 2019 - Today"
    description: "SDE Intern at HackerRank"
  - image: "/img/timeline/pesu.png"
    date: "August 2018 - December 2018"
    description: "Teaching Assistant for the Big Data course at PESU"
  - image: "/img/timeline/IBM.png"
    date: "May 2018 - August 2018"
    description: "SDE Intern at IBM ISL, Bangalore"
  - image: "/img/timeline/ccbd.png"
    date: "May 2017 - May 2018"
    description: "Research Intern at Center for Cloud Computing and Big Data, PESU"
  - image: "/img/timeline/hello-world.png"
    date: "December 2015"
    description: "Started coding!"  

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "aditisrinivas97@gmail.com"

################
# Author Blurb #
################

author_blurb: "Aditi Srinivas is an awesome person. She loves dogs. In her spare time, Aditi likes to binge watch shows on Netflix."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/aditisrinivas97/"
  - title: "github"
    url: "https://github.com/aditisrinivas97"
  - title: "instagram"
    url: "https://www.instagram.com/aditisrinivas1902/?hl=en"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: aditisrinivas
keybase-in-social: False
keybase-in-footer: False

################################################################################

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'
  
  
# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
